### PR TITLE
Switching to version catalog

### PR DESCRIPTION
**Pull request by gull192**
Switching from buildSrc to version catalog

### CODE REVIEW

**Comment by gull192** [comment]
Another project with an application on tv is placed in a separate module

**Comment by UserNameMax** [comment]
When you close this pr?

**Comment by Radch-enko** [comment]
Resolve conflicts and merge

**Review by Radch-enko — APPROVED** [review]

**Comment by UserNameMax** [comment]
This pr is outdated. It’s easier make switching from actual develop than to resolve conflicts

**Pull request closed without merging**
